
# 漫画网站配置文件

app:
  host: ":8084"
  debug: true
  baseurl: "http://fr.ninemanga.com/category/index_%v.html"
  language: "en"
  s3url: "https://pre-europe.s3.eu-central-1.amazonaws.com/es-comic/img-45/"

mysql:
#  dsn: "root:mlbj8888@(127.0.0.1:3306)/pre_cartoon?charset=utf8"
  dsn: "root:123456@(127.0.0.1:3306)/pre_cartoon_fr?charset=utf8"

pgsql:
  dsn: "host=127.0.0.1 user=postgres dbname=pre_comic sslmode=disable password=123456"
  max_idle: 10 # 最大闲置链接数
  max_open: 100 # 最大链接数
  time_out: 4 # 超时 Hour

redis:
  maxidle: 50 # 连接池中最大空闲连接数量
  max_active: 30 # 最大连接数量
  idle_timeout: 300 # 最大超时时间(s)
  port: "127.0.0.1:6379"



